# Playbook to setup workstation and create osp network, router, SG and ssh keypair

- hosts: workstation
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-c209.rhpds.opentlc.com"
       group: workstation


- hosts: workstation
  become: yes
  roles:
    - setup-workstation

- import_playbook: site-install-isolated-node.yml 

