- hosts: localhost
  gather_facts: false
  tasks:
  - name: display the hostname
    shell: hostname
    register: name
  - debug: 
      var: name
    
  - name: Run Ansible Tower setup
    become: true
    become_user: root
    shell: /root/ansible-tower-setup-latest/setup.sh
    async: 3600
    poll: 36
  
